-- liquibase formatted sql

-- changeset vbanasevych:1

-- Користувачі
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'CLIENT', 'LAWYER'))
    );

-- Адвокати
CREATE TABLE IF NOT EXISTS lawyers (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    hourly_rate DECIMAL(10, 2),
    city VARCHAR(100),
    bio TEXT
    );

-- Довідник Категорій
CREATE TABLE IF NOT EXISTS case_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
    );

-- Спеціалізації
CREATE TABLE IF NOT EXISTS lawyer_categories (
    lawyer_id BIGINT NOT NULL REFERENCES lawyers(user_id) ON DELETE CASCADE,
    case_category_id BIGINT NOT NULL REFERENCES case_categories(id) ON DELETE CASCADE,
    PRIMARY KEY (lawyer_id, case_category_id)
    );

-- Справи
CREATE TABLE legal_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_number VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP,
    edited_at TIMESTAMP,
    status VARCHAR(50) NOT NULL CHECK (status IN ('NEW', 'ACCEPTED', 'DECLINED', 'IN_PROGRESS', 'COMPLETED')),

    -- Зовнішні ключі
    client_id BIGINT NOT NULL REFERENCES users(id),
    lawyer_id BIGINT REFERENCES lawyers(user_id),
    case_category_id BIGINT REFERENCES case_categories(id)
);

-- Послуги
CREATE TABLE case_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    date_added DATE DEFAULT CURRENT_DATE,
    legal_case_id BIGINT NOT NULL REFERENCES legal_cases(id) ON DELETE CASCADE
);

-- Судові засідання
CREATE TABLE hearings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hearing_date TIMESTAMP NOT NULL,
    place VARCHAR(255),
    result VARCHAR(50),
    legal_case_id BIGINT NOT NULL REFERENCES legal_cases(id) ON DELETE CASCADE
);

-- Рахунки
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount DECIMAL(10, 2) NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_paid BOOLEAN DEFAULT FALSE,
    legal_case_id BIGINT NOT NULL UNIQUE REFERENCES legal_cases(id) ON DELETE CASCADE
);